[package]
name = "gattic_errors"
description = "Gatti's compiler diagnostic and error system."

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
termcolor.workspace = true
