[package]
name = "gattic_parser"
description = "Gatti's parser crate."

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
termcolor.workspace = true

# internal libs
gattic_errors.workspace = true
gattic_tokens.workspace = true
