[package]
name = "gattic_lexer"
description = "Gatti's lexer library."

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]

# internal libs
gattic_errors.workspace = true
gattic_tokens.workspace = true
